name: Build and Publish py-ir2vec Wheel

on:
  push:
    branches:
      - ir2vec_python_bindings
    paths:
      - 'llvm/tools/llvm-ir2vec/**'
      - '.github/workflows/build-py-ir2vec-wheel.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybind11 setuptools wheel build auditwheel
    
    - name: Build LLVM and py_ir2vec
      run: |
        cd llvm/tools/llvm-ir2vec/bindings
        chmod +x build_llvm.sh build_wheel.sh
        ./build_llvm.sh
        ./build_wheel.sh
    
    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v4
      with:
        name: py-ir2vec-wheel
        path: llvm/tools/llvm-ir2vec/bindings/wheels/*.whl
        if-no-files-found: error
  
  publish:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    
    steps:
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        name: py-ir2vec-wheel
        path: wheels
    
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        packages-dir: wheels/
        skip-existing: true
        verbose: true